<a href="https://colab.research.google.com/github/gopikiran22001/ADS/blob/main/lab12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import json
def check(data):
  if isinstance(data,(dict,list)):
    for val in data:
      if isinstance(data,dict):
        val=data[val]
      if isinstance(val,(dict,list)) or check(val):
        return True
  return False
def comp_json(st):
  try:
    data=json.loads(st)
    return check(data)
  except Exception as e:
    print(e)
    return False
d1='{"1":"cat","2":"dog","3":"cow"}'
d2='{"1":["A","B","C"],"2":["D","E","F"],"3":["G","H","I"]}'
print(comp_json(d1))
print(comp_json(d2))

False
True


In [12]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.size)

2
(2, 3)
int64
6


In [17]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[:2,1:])
print(b[(1,1)],b[(2,2)])
print(b[b<=5])

[[2 3]
 [5 6]]
5 9
[1 2 3 4 5]


In [18]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min())
print(b.max())
print(b.cumsum())


[12 15 18]
[ 6 15 24]
1
9
[ 1  3  6 10 15 21 28 36 45]


In [31]:
import pandas as pd
d={"c++":[69,58,78,98,52,56,78,45,25,11],"kotlin":[89,69,78,56,23,63,96,89,75,48],"java":[89,69,75,89,65,23,12,39,85,56],"python":[59,84,12,65,62,36,78,58,91,56],"c#":[85,96,36,14,25,65,45,78,85,85]}
df=pd.DataFrame(d,index=range(1,11))
print(df)
print()
print(df.head())
print()
print(df.tail())
print()
print(df["c#"])
print()
print(df.loc[5])
print()
print(df.iloc[1])
print()
print(df[df>50])
print()
print(df[1:6])
print()

    c++  kotlin  java  python  c#
1    69      89    89      59  85
2    58      69    69      84  96
3    78      78    75      12  36
4    98      56    89      65  14
5    52      23    65      62  25
6    56      63    23      36  65
7    78      96    12      78  45
8    45      89    39      58  78
9    25      75    85      91  85
10   11      48    56      56  85

   c++  kotlin  java  python  c#
1   69      89    89      59  85
2   58      69    69      84  96
3   78      78    75      12  36
4   98      56    89      65  14
5   52      23    65      62  25

    c++  kotlin  java  python  c#
6    56      63    23      36  65
7    78      96    12      78  45
8    45      89    39      58  78
9    25      75    85      91  85
10   11      48    56      56  85

1     85
2     96
3     36
4     14
5     25
6     65
7     45
8     78
9     85
10    85
Name: c#, dtype: int64

c++       52
kotlin    23
java      65
python    62
c#        25
Name: 5, dtype: int64

c++       58
kotlin